# Generated by Django 3.2.3 on 2021-07-03 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('additions', '0002_tool'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, default='no-image.jpg', upload_to='travel_photos/')),
            ],
        ),
    ]
