# Generated by Django 3.2.3 on 2021-12-09 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('additions', '0003_travelphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='tool_num',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
