# Generated by Django 3.2.3 on 2021-06-05 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_category_comment_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
        migrations.RemoveField(
            model_name='post',
            name='categories',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
