# Generated by Django 3.2.3 on 2021-11-29 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('additions', '0003_travelphoto'),
        ('projects', '0006_projectimages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='technology',
            new_name='product_used',
        ),
        migrations.AddField(
            model_name='project',
            name='tool_used',
            field=models.ManyToManyField(related_name='tools', to='additions.Tool'),
        ),
    ]
