# Generated by Django 3.2.3 on 2021-11-29 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20211129_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='product_used',
        ),
    ]
