# Generated by Django 3.2.3 on 2021-12-09 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('additions', '0004_alter_tool_tool_num'),
        ('projects', '0008_remove_project_product_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='tool_used',
            field=models.ManyToManyField(blank=True, related_name='tools', to='additions.Tool'),
        ),
    ]
